### ISSUE TITLE
Example of applying raw data

### ISSUE THREAD

**Issue by alexxony** [Aura-healthcare/ecg_qc#9]
I have single line ecg data; I used neurokit. But it evaluated incorrectly in Bluetooth disconnection period. 
And Their reference:  SQI Quality Evaluation Mechanism of Single-Lead ECG Signal Based on Simple Heuristic Fusion and Fuzzy Comprehensive Evaluation, it cited only 20. 

Can you explain how to apply my data on your package? and what is your reference?

**Comment by alexisgcomte** [comment]
Hello alexxony,

Our reference is [Brno University of Technology ECG Quality Database (BUT QDB)](https://doi.org/10.13026/kah4-0w24).

Our library focus mainly on physical signal noise, ie electrocardiogram noise. It may be caused for exemple by movements of tje recording device. As our ML models are trained for this, it may not be very efficient on your specific issue, which has more to do with network jittering. Still, you can try !
- initialize ecg_qc class as in readme, with proper sampling frequency
- you have to spit your ecg_qc signal into samples of fixed seconds. For last pip version the ML model is trained of a time window is 9 seconds
- use `get_signal_quality(sample_signal)` to get the binary quality of the signal. It will compute SQIs and use trained model to classify noise.

The libary is still beta and might not suit your specific issue, however if you want we can help you develop this part. It would improve usability of the library!

Best regards,

Alexis
